<?php
/**
 * Language Manager - Language Presets
 *
 * Maps IETF language codes (e.g. bg-bg) to their OpenCart locale metadata.
 * Each entry provides sane defaults so the admin never needs to type locale
 * strings, charset or date-format values manually.
 *
 * Fields per entry:
 *  name         - Language name in English
 *  native_name  - Language name in native script
 *  code         - Short language code stored in oc_language.code (bg, en, de …)
 *  locale       - Full locale string(s) accepted by setlocale()
 *  image        - Flag filename under image/flags/ (xx.png)
 *  directory    - Sub-directory name under admin/language/ and catalog/language/
 *  charset      - Always UTF-8 for modern OpenCart
 *  date_format_short  - PHP date() short format
 *  date_format_long   - PHP date() long format
 *  time_format        - PHP date() time format
 *  datetime_format    - PHP date() full datetime format
 *  decimal_point      - Decimal separator character
 *  thousand_point     - Thousands separator character
 *  direction          - 'ltr' or 'rtl'
 *  sort_order         - Default sort order (alphabetical by English name)
 *  status             - 1 = enabled by default when installed
 */
return [

    // ── European languages ───────────────────────────────────────────────────

    'bg-bg' => [
        'name'              => 'Bulgarian',
        'native_name'       => 'Български',
        'code'              => 'bg',
        'locale'            => 'bg_BG.UTF-8,bg_BG,bg-bg,bulgarian',
        'image'             => 'bg.png',
        'directory'         => 'bg-bg',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l dS F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'ltr',
        'sort_order'        => 10,
        'status'            => 1,
    ],

    'cs-cz' => [
        'name'              => 'Czech',
        'native_name'       => 'Čeština',
        'code'              => 'cs',
        'locale'            => 'cs_CZ.UTF-8,cs_CZ,cs-cz,czech',
        'image'             => 'cz.png',
        'directory'         => 'cs-cz',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l dS F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 20,
        'status'            => 1,
    ],

    'da-dk' => [
        'name'              => 'Danish',
        'native_name'       => 'Dansk',
        'code'              => 'da',
        'locale'            => 'da_DK.UTF-8,da_DK,da-dk,danish',
        'image'             => 'dk.png',
        'directory'         => 'da-dk',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l dS F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 25,
        'status'            => 1,
    ],

    'de-de' => [
        'name'              => 'German',
        'native_name'       => 'Deutsch',
        'code'              => 'de',
        'locale'            => 'de_DE.UTF-8,de_DE,de-de,german',
        'image'             => 'de.png',
        'directory'         => 'de-de',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l, d. F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 30,
        'status'            => 1,
    ],

    'de-at' => [
        'name'              => 'German (Austria)',
        'native_name'       => 'Deutsch (Österreich)',
        'code'              => 'de',
        'locale'            => 'de_AT.UTF-8,de_AT,de-at',
        'image'             => 'at.png',
        'directory'         => 'de-at',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l, d. F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 31,
        'status'            => 1,
    ],

    'de-ch' => [
        'name'              => 'German (Switzerland)',
        'native_name'       => 'Deutsch (Schweiz)',
        'code'              => 'de',
        'locale'            => 'de_CH.UTF-8,de_CH,de-ch',
        'image'             => 'ch.png',
        'directory'         => 'de-ch',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l, d. F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => '\'',
        'direction'         => 'ltr',
        'sort_order'        => 32,
        'status'            => 1,
    ],

    'el-gr' => [
        'name'              => 'Greek',
        'native_name'       => 'Ελληνικά',
        'code'              => 'el',
        'locale'            => 'el_GR.UTF-8,el_GR,el-gr,greek',
        'image'             => 'gr.png',
        'directory'         => 'el-gr',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l dS F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 35,
        'status'            => 1,
    ],

    'en-gb' => [
        'name'              => 'English (UK)',
        'native_name'       => 'English (UK)',
        'code'              => 'en',
        'locale'            => 'en_GB.UTF-8,en_GB,en-gb,english',
        'image'             => 'gb.png',
        'directory'         => 'en-gb',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l dS F Y',
        'time_format'       => 'h:i:s A',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'ltr',
        'sort_order'        => 1,
        'status'            => 1,
    ],

    'en-us' => [
        'name'              => 'English (US)',
        'native_name'       => 'English (US)',
        'code'              => 'en',
        'locale'            => 'en_US.UTF-8,en_US,en-us,english',
        'image'             => 'us.png',
        'directory'         => 'en-us',
        'charset'           => 'UTF-8',
        'date_format_short' => 'm/d/Y',
        'date_format_long'  => 'l, F jS Y',
        'time_format'       => 'h:i:s A',
        'datetime_format'   => 'm/d/Y h:i:s A',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'ltr',
        'sort_order'        => 2,
        'status'            => 1,
    ],

    'es-es' => [
        'name'              => 'Spanish (Spain)',
        'native_name'       => 'Español (España)',
        'code'              => 'es',
        'locale'            => 'es_ES.UTF-8,es_ES,es-es,spanish',
        'image'             => 'es.png',
        'directory'         => 'es-es',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l, d \d\e F \d\e Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 40,
        'status'            => 1,
    ],

    'es-mx' => [
        'name'              => 'Spanish (Mexico)',
        'native_name'       => 'Español (México)',
        'code'              => 'es',
        'locale'            => 'es_MX.UTF-8,es_MX,es-mx',
        'image'             => 'mx.png',
        'directory'         => 'es-mx',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l, d \d\e F \d\e Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'ltr',
        'sort_order'        => 41,
        'status'            => 1,
    ],

    'et-ee' => [
        'name'              => 'Estonian',
        'native_name'       => 'Eesti',
        'code'              => 'et',
        'locale'            => 'et_EE.UTF-8,et_EE,et-ee,estonian',
        'image'             => 'ee.png',
        'directory'         => 'et-ee',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l, d. F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 45,
        'status'            => 1,
    ],

    'fi-fi' => [
        'name'              => 'Finnish',
        'native_name'       => 'Suomi',
        'code'              => 'fi',
        'locale'            => 'fi_FI.UTF-8,fi_FI,fi-fi,finnish',
        'image'             => 'fi.png',
        'directory'         => 'fi-fi',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l d. F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 50,
        'status'            => 1,
    ],

    'fr-fr' => [
        'name'              => 'French',
        'native_name'       => 'Français',
        'code'              => 'fr',
        'locale'            => 'fr_FR.UTF-8,fr_FR,fr-fr,french',
        'image'             => 'fr.png',
        'directory'         => 'fr-fr',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l d F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 55,
        'status'            => 1,
    ],

    'fr-be' => [
        'name'              => 'French (Belgium)',
        'native_name'       => 'Français (Belgique)',
        'code'              => 'fr',
        'locale'            => 'fr_BE.UTF-8,fr_BE,fr-be',
        'image'             => 'be.png',
        'directory'         => 'fr-be',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l d F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 56,
        'status'            => 1,
    ],

    'hr-hr' => [
        'name'              => 'Croatian',
        'native_name'       => 'Hrvatski',
        'code'              => 'hr',
        'locale'            => 'hr_HR.UTF-8,hr_HR,hr-hr,croatian',
        'image'             => 'hr.png',
        'directory'         => 'hr-hr',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y.',
        'date_format_long'  => 'l, d. F Y.',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y. H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 60,
        'status'            => 1,
    ],

    'hu-hu' => [
        'name'              => 'Hungarian',
        'native_name'       => 'Magyar',
        'code'              => 'hu',
        'locale'            => 'hu_HU.UTF-8,hu_HU,hu-hu,hungarian',
        'image'             => 'hu.png',
        'directory'         => 'hu-hu',
        'charset'           => 'UTF-8',
        'date_format_short' => 'Y.m.d.',
        'date_format_long'  => 'Y. F d., l',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'Y.m.d. H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 65,
        'status'            => 1,
    ],

    'it-it' => [
        'name'              => 'Italian',
        'native_name'       => 'Italiano',
        'code'              => 'it',
        'locale'            => 'it_IT.UTF-8,it_IT,it-it,italian',
        'image'             => 'it.png',
        'directory'         => 'it-it',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l d F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 70,
        'status'            => 1,
    ],

    'lt-lt' => [
        'name'              => 'Lithuanian',
        'native_name'       => 'Lietuvių',
        'code'              => 'lt',
        'locale'            => 'lt_LT.UTF-8,lt_LT,lt-lt,lithuanian',
        'image'             => 'lt.png',
        'directory'         => 'lt-lt',
        'charset'           => 'UTF-8',
        'date_format_short' => 'Y-m-d',
        'date_format_long'  => 'Y m d, l',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'Y-m-d H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 75,
        'status'            => 1,
    ],

    'lv-lv' => [
        'name'              => 'Latvian',
        'native_name'       => 'Latviešu',
        'code'              => 'lv',
        'locale'            => 'lv_LV.UTF-8,lv_LV,lv-lv,latvian',
        'image'             => 'lv.png',
        'directory'         => 'lv-lv',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y.',
        'date_format_long'  => 'Y. \g\a\d\a d. F, l',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y. H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 76,
        'status'            => 1,
    ],

    'mk-mk' => [
        'name'              => 'Macedonian',
        'native_name'       => 'Македонски',
        'code'              => 'mk',
        'locale'            => 'mk_MK.UTF-8,mk_MK,mk-mk,macedonian',
        'image'             => 'mk.png',
        'directory'         => 'mk-mk',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l dS F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 77,
        'status'            => 1,
    ],

    'nl-nl' => [
        'name'              => 'Dutch',
        'native_name'       => 'Nederlands',
        'code'              => 'nl',
        'locale'            => 'nl_NL.UTF-8,nl_NL,nl-nl,dutch',
        'image'             => 'nl.png',
        'directory'         => 'nl-nl',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd-m-Y',
        'date_format_long'  => 'l d F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd-m-Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 80,
        'status'            => 1,
    ],

    'no-no' => [
        'name'              => 'Norwegian',
        'native_name'       => 'Norsk',
        'code'              => 'no',
        'locale'            => 'nb_NO.UTF-8,nb_NO,no_NO,no-no,norwegian',
        'image'             => 'no.png',
        'directory'         => 'no-no',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l d. F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 85,
        'status'            => 1,
    ],

    'pl-pl' => [
        'name'              => 'Polish',
        'native_name'       => 'Polski',
        'code'              => 'pl',
        'locale'            => 'pl_PL.UTF-8,pl_PL,pl-pl,polish',
        'image'             => 'pl.png',
        'directory'         => 'pl-pl',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l, d F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 90,
        'status'            => 1,
    ],

    'pt-pt' => [
        'name'              => 'Portuguese (Portugal)',
        'native_name'       => 'Português (Portugal)',
        'code'              => 'pt',
        'locale'            => 'pt_PT.UTF-8,pt_PT,pt-pt,portuguese',
        'image'             => 'pt.png',
        'directory'         => 'pt-pt',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l, d \d\e F \d\e Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 95,
        'status'            => 1,
    ],

    'pt-br' => [
        'name'              => 'Portuguese (Brazil)',
        'native_name'       => 'Português (Brasil)',
        'code'              => 'pt',
        'locale'            => 'pt_BR.UTF-8,pt_BR,pt-br',
        'image'             => 'br.png',
        'directory'         => 'pt-br',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l, d \d\e F \d\e Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 96,
        'status'            => 1,
    ],

    'ro-ro' => [
        'name'              => 'Romanian',
        'native_name'       => 'Română',
        'code'              => 'ro',
        'locale'            => 'ro_RO.UTF-8,ro_RO,ro-ro,romanian',
        'image'             => 'ro.png',
        'directory'         => 'ro-ro',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l, d F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 100,
        'status'            => 1,
    ],

    'ru-ru' => [
        'name'              => 'Russian',
        'native_name'       => 'Русский',
        'code'              => 'ru',
        'locale'            => 'ru_RU.UTF-8,ru_RU,ru-ru,russian',
        'image'             => 'ru.png',
        'directory'         => 'ru-ru',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l, d F Y \г.',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 105,
        'status'            => 1,
    ],

    'sk-sk' => [
        'name'              => 'Slovak',
        'native_name'       => 'Slovenčina',
        'code'              => 'sk',
        'locale'            => 'sk_SK.UTF-8,sk_SK,sk-sk,slovak',
        'image'             => 'sk.png',
        'directory'         => 'sk-sk',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l, d. F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 110,
        'status'            => 1,
    ],

    'sl-si' => [
        'name'              => 'Slovenian',
        'native_name'       => 'Slovenščina',
        'code'              => 'sl',
        'locale'            => 'sl_SI.UTF-8,sl_SI,sl-si,slovenian',
        'image'             => 'si.png',
        'directory'         => 'sl-si',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l, d. F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 111,
        'status'            => 1,
    ],

    'sq-al' => [
        'name'              => 'Albanian',
        'native_name'       => 'Shqip',
        'code'              => 'sq',
        'locale'            => 'sq_AL.UTF-8,sq_AL,sq-al,albanian',
        'image'             => 'al.png',
        'directory'         => 'sq-al',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l d F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 112,
        'status'            => 1,
    ],

    'sr-rs' => [
        'name'              => 'Serbian',
        'native_name'       => 'Srpski',
        'code'              => 'sr',
        'locale'            => 'sr_RS.UTF-8,sr_RS,sr-rs,serbian',
        'image'             => 'rs.png',
        'directory'         => 'sr-rs',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y.',
        'date_format_long'  => 'l, d. F Y.',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y. H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 115,
        'status'            => 1,
    ],

    'sv-se' => [
        'name'              => 'Swedish',
        'native_name'       => 'Svenska',
        'code'              => 'sv',
        'locale'            => 'sv_SE.UTF-8,sv_SE,sv-se,swedish',
        'image'             => 'se.png',
        'directory'         => 'sv-se',
        'charset'           => 'UTF-8',
        'date_format_short' => 'Y-m-d',
        'date_format_long'  => 'l d F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'Y-m-d H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 120,
        'status'            => 1,
    ],

    'tr-tr' => [
        'name'              => 'Turkish',
        'native_name'       => 'Türkçe',
        'code'              => 'tr',
        'locale'            => 'tr_TR.UTF-8,tr_TR,tr-tr,turkish',
        'image'             => 'tr.png',
        'directory'         => 'tr-tr',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l, d F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 125,
        'status'            => 1,
    ],

    'uk-ua' => [
        'name'              => 'Ukrainian',
        'native_name'       => 'Українська',
        'code'              => 'uk',
        'locale'            => 'uk_UA.UTF-8,uk_UA,uk-ua,ukrainian',
        'image'             => 'ua.png',
        'directory'         => 'uk-ua',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd.m.Y',
        'date_format_long'  => 'l, d F Y \р.',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd.m.Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => ' ',
        'direction'         => 'ltr',
        'sort_order'        => 130,
        'status'            => 1,
    ],

    // ── Middle-East / RTL ────────────────────────────────────────────────────

    'ar-sa' => [
        'name'              => 'Arabic',
        'native_name'       => 'العربية',
        'code'              => 'ar',
        'locale'            => 'ar_SA.UTF-8,ar_SA,ar-sa,arabic',
        'image'             => 'sa.png',
        'directory'         => 'ar-sa',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l dS F Y',
        'time_format'       => 'h:i:s A',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'rtl',
        'sort_order'        => 5,
        'status'            => 1,
    ],

    'fa-ir' => [
        'name'              => 'Persian',
        'native_name'       => 'فارسی',
        'code'              => 'fa',
        'locale'            => 'fa_IR.UTF-8,fa_IR,fa-ir,persian',
        'image'             => 'ir.png',
        'directory'         => 'fa-ir',
        'charset'           => 'UTF-8',
        'date_format_short' => 'Y/m/d',
        'date_format_long'  => 'l dS F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'Y/m/d H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'rtl',
        'sort_order'        => 48,
        'status'            => 1,
    ],

    'he-il' => [
        'name'              => 'Hebrew',
        'native_name'       => 'עברית',
        'code'              => 'he',
        'locale'            => 'he_IL.UTF-8,he_IL,he-il,hebrew',
        'image'             => 'il.png',
        'directory'         => 'he-il',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l dS F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'rtl',
        'sort_order'        => 62,
        'status'            => 1,
    ],

    // ── Asian languages ──────────────────────────────────────────────────────

    'id-id' => [
        'name'              => 'Indonesian',
        'native_name'       => 'Bahasa Indonesia',
        'code'              => 'id',
        'locale'            => 'id_ID.UTF-8,id_ID,id-id,indonesian',
        'image'             => 'id.png',
        'directory'         => 'id-id',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l, d F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 67,
        'status'            => 1,
    ],

    'ja-jp' => [
        'name'              => 'Japanese',
        'native_name'       => '日本語',
        'code'              => 'ja',
        'locale'            => 'ja_JP.UTF-8,ja_JP,ja-jp,japanese',
        'image'             => 'jp.png',
        'directory'         => 'ja-jp',
        'charset'           => 'UTF-8',
        'date_format_short' => 'Y/m/d',
        'date_format_long'  => 'Y年m月d日 l',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'Y/m/d H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'ltr',
        'sort_order'        => 72,
        'status'            => 1,
    ],

    'ko-kr' => [
        'name'              => 'Korean',
        'native_name'       => '한국어',
        'code'              => 'ko',
        'locale'            => 'ko_KR.UTF-8,ko_KR,ko-kr,korean',
        'image'             => 'kr.png',
        'directory'         => 'ko-kr',
        'charset'           => 'UTF-8',
        'date_format_short' => 'Y.m.d',
        'date_format_long'  => 'Y년 m월 d일 l',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'Y.m.d H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'ltr',
        'sort_order'        => 73,
        'status'            => 1,
    ],

    'ms-my' => [
        'name'              => 'Malay',
        'native_name'       => 'Bahasa Melayu',
        'code'              => 'ms',
        'locale'            => 'ms_MY.UTF-8,ms_MY,ms-my,malay',
        'image'             => 'my.png',
        'directory'         => 'ms-my',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l, d F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'ltr',
        'sort_order'        => 78,
        'status'            => 1,
    ],

    'th-th' => [
        'name'              => 'Thai',
        'native_name'       => 'ภาษาไทย',
        'code'              => 'th',
        'locale'            => 'th_TH.UTF-8,th_TH,th-th,thai',
        'image'             => 'th.png',
        'directory'         => 'th-th',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l dS F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'ltr',
        'sort_order'        => 122,
        'status'            => 1,
    ],

    'vi-vn' => [
        'name'              => 'Vietnamese',
        'native_name'       => 'Tiếng Việt',
        'code'              => 'vi',
        'locale'            => 'vi_VN.UTF-8,vi_VN,vi-vn,vietnamese',
        'image'             => 'vn.png',
        'directory'         => 'vi-vn',
        'charset'           => 'UTF-8',
        'date_format_short' => 'd/m/Y',
        'date_format_long'  => 'l, d F Y',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'd/m/Y H:i:s',
        'decimal_point'     => ',',
        'thousand_point'    => '.',
        'direction'         => 'ltr',
        'sort_order'        => 135,
        'status'            => 1,
    ],

    'zh-cn' => [
        'name'              => 'Chinese (Simplified)',
        'native_name'       => '中文(简体)',
        'code'              => 'zh',
        'locale'            => 'zh_CN.UTF-8,zh_CN,zh-cn,chinese',
        'image'             => 'cn.png',
        'directory'         => 'zh-cn',
        'charset'           => 'UTF-8',
        'date_format_short' => 'Y-m-d',
        'date_format_long'  => 'Y年m月d日 l',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'Y-m-d H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'ltr',
        'sort_order'        => 140,
        'status'            => 1,
    ],

    'zh-tw' => [
        'name'              => 'Chinese (Traditional)',
        'native_name'       => '中文(繁體)',
        'code'              => 'zh',
        'locale'            => 'zh_TW.UTF-8,zh_TW,zh-tw',
        'image'             => 'tw.png',
        'directory'         => 'zh-tw',
        'charset'           => 'UTF-8',
        'date_format_short' => 'Y/m/d',
        'date_format_long'  => 'Y年m月d日 l',
        'time_format'       => 'H:i:s',
        'datetime_format'   => 'Y/m/d H:i:s',
        'decimal_point'     => '.',
        'thousand_point'    => ',',
        'direction'         => 'ltr',
        'sort_order'        => 141,
        'status'            => 1,
    ],
];
